services:
  proxy:
    image: traefik:3.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 8080
        published: 8090
        protocol: tcp
        mode: host
    labels:
      - traefik.enable=true
      - traefik.constraint-label=traefik-public
      - traefik.http.middlewares.https-redirect.contenttype.autodetect=false
    command:
      - --providers.docker
      - --providers.docker.constraints=Label(`traefik.constraint-label`, `traefik-public`)
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --accesslog
      - --log
      - --log.level=DEBUG
      - --api
      - --api.insecure=true
    networks:
      - traefik-public
      - default

  backend:
    platform: linux/amd64 # This is required for M1 Macs
    restart: always
    container_name: express-boilerplate
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - HOST=${HOST}
      - CORS_WHITELIST=${CORS_WHITELIST}

networks:
  traefik-public:
    external: false
