name: 🐛 Bug Report
description: Report a possible bug or regression
title: "🐛 <TITLE>"
labels: ["S-To triage"]
body:
  - type: markdown
    attributes:
      value: Thank you for submitting the bug! We'll try to triage it ASAP!
  - type: markdown
    attributes:
      value: |
        Bug reports that don't follow this template will be closed.
        Please provide a clear and concise description of what the bug is.
  - type: textarea
    id: environment
    attributes:
      label: Environment information
      description: Operating system, browser, and any other relevant information
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A summary of the bug
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Detailed steps to reproduce the bug
    validations:
      required: true
