name: Build Express Bdoilerplate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  STACK_NAME: express-bdoilerplate
  DOMAIN: localhost
  NODE_ENV: development
  PORT: 8080
  HOST: localhost
  CORS_WHITELIST: '*'
  API_KEY: 'secret'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.6.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint code
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test
