name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v4

      # Login step only executed for pushes to main
      - name: Login to GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}

      # Convert repository name to lowercase
      - name: Set repository name to lowercase
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # Build and tag the production Docker image
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag ghcr.io/${{ env.REPO_NAME }}:${{ github.sha }}
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            docker tag ghcr.io/${{ env.REPO_NAME }}:${{ github.sha }} ghcr.io/${{ env.REPO_NAME }}:latest
          fi

      # Push the production Docker image
      - name: Push the Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ghcr.io/${{ env.REPO_NAME }}:${{ github.sha }}
          docker push ghcr.io/${{ env.REPO_NAME }}:latest
